### ISSUE TITLE
GH-FY16 Maris  Alignment Harmonization

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#80]

**Comment by yuankunzhu** [comment]
This is HudsonAlpha data, from multiple uploads. Might need some investigation before kickoff

**Comment by migbro** [comment]
Bo set up the project and migrated the files in, and collected read group and fastq info for each BS ID.  I have setup and kicked off running harmonization using a slightly modified version (increased bwa cores) for fq-to-cram-to gvcf pipeline

**Comment by migbro** [comment]
Mostly complete - a quick note for failed tasks to clear out files that might have been generated/remained so as to not waste space

**Comment by migbro** [comment]
I cleared out some files from old failed tasks.  Tasks related to BS_2E03PR1Q failed twice.  A closer look at the instance metrics reveal that it probably ran out of disk space.  Bo was able to save the bam output from sambamba_merge and suggested I run from there.  Running a modified pipe starting at the sort step with that file, and increase disk from 850GB to 1024GB.  I also increased ram that sambamba sort uses from 10GB to 48GB since the instance has 60GB of ram.  Hopefully those two fixes will allow this sample to complete successfully.
